const images = [
   {
      name: "Sunset at the lake",
      src: "img_0001.JPG",
      column: 1,
      gridkey: "2x2",
   },
   {
      name: "Florence",
      src: "img_0002.JPG",
      column: 1,
      gridkey: "2x1",
   },
   {
      name: "Morning glory",
      src: "img_0003.JPG",
      column: 1,
      gridkey: "1x1",
   },
   {
      name: "Like Van Gogh",
      src: "img_0004.JPG",
      column: 2,
      gridkey: "1x1",
   },
   {
      name: "Purple at the lake",
      src: "img_0005.JPG",
      column: 2,
      gridkey: "1x1",
   },
   {
      name: "Waterfall",
      src: "img_0006.JPG",
      column: 2,
      gridkey: "1x1",
   },
   {
      name: "Sunset in Cancún",
      src: "img_0007.JPG",
      column: 3,
      gridkey: "1x1",
   },
   {
      name: "Morning in Cancún",
      src: "img_0008.JPG",
      column: 3,
      gridkey: "2x2",
   },
   {
      name: "Lucerna",
      src: "img_0009.JPG",
      column: 3,
      gridkey: "1x1",
   },
   {
      name: "Lucerna (Horizontal)",
      src: "img_0010.JPG",
      column: 4,
      gridkey: "1x1",
   },
   {
      name: "Lucerna 2",
      src: "img_0011.JPG",
      column: 4,
      gridkey: "2x2",
   },
   {
      name: "Castle",
      src: "img_0012.JPG",
      column: 4,
      gridkey: "1x1",
   },
   {
      name: "Love beneath trees",
      src: "img_0013.png",
      column: 1,
      gridkey: "2x2",
   },
   {
      name: "Claridad",
      src: "img_0014.png",
      column: 1,
      gridkey: "1x1",
   },
   {
      name: "Las Vegas",
      src: "img_0015.png",
      column: 1,
      gridkey: "2x2",
   },
   {
      name: "Las Vegas",
      src: "img_0016.png",
      column: 4,
      gridkey: "1x1",
   },
   {
      name: "Pinky pie",
      src: "img_0017.png",
      column: 2,
      gridkey: "2x1",
   },
   {
      name: "Il Milano",
      src: "img_0018.png",
      column: 2,
      gridkey: "1x1",
   },
   {
      name: "Venezia",
      src: "img_0019.png",
      column: 3,
      gridkey: "1x1",
   },
   {
      name: "The Forest",
      src: "img_0020.png",
      column: 3,
      gridkey: "1x1",
   },
   {
      name: "Hawai'i",
      src: "img_0021.png",
      column: 3,
      gridkey: "2x2",
   },
   {
      name: "Florencia",
      src: "img_0022.png",
      column: 4,
      gridkey: "1x1",
   },
   {
      name: "Florencia",
      src: "img_0023.png",
      column: 4,
      gridkey: "2x2",
   },
   {
      name: "Magic on the trees",
      src: "img_0024.png",
      column: 2,
      gridkey: "1x1",
   },
];
